// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteBackEndCSharp.Context;

#nullable disable

namespace TesteBackEndCSharp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220610020916_CriarTabela")]
    partial class CriarTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TesteBackEndCSharp.Models.Money", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("data_fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Money");
                });
#pragma warning restore 612, 618
        }
    }
}
